Repository BCSD-Android-Study/study-android, pull requests merged in 2024-05, with the labels that each got.

#5 [#4] 초기 프로젝트 세팅
  dohyeok/AndroidStudy/.gitignore
  dohyeok/AndroidStudy/.idea/.gitignore
  dohyeok/AndroidStudy/.idea/.name
  dohyeok/AndroidStudy/.idea/compiler.xml
  dohyeok/AndroidStudy/.idea/deploymentTargetDropDown.xml
  dohyeok/AndroidStudy/.idea/gradle.xml
  dohyeok/AndroidStudy/.idea/kotlinc.xml
  dohyeok/AndroidStudy/.idea/migrations.xml
  dohyeok/AndroidStudy/.idea/misc.xml
  dohyeok/AndroidStudy/.idea/vcs.xml
  dohyeok/AndroidStudy/app/.gitignore
  dohyeok/AndroidStudy/app/build.gradle.kts
  dohyeok/AndroidStudy/app/proguard-rules.pro
  dohyeok/AndroidStudy/app/src/androidTest/java/com/dohyeok/androidstudy/ExampleInstrumentedTest.kt
  dohyeok/AndroidStudy/app/src/main/AndroidManifest.xml
  dohyeok/AndroidStudy/app/src/main/java/com/dohyeok/androidstudy/MainActivity.kt
  dohyeok/AndroidStudy/app/src/main/res/drawable/ic_launcher_background.xml
  dohyeok/AndroidStudy/app/src/main/res/drawable/ic_launcher_foreground.xml
  dohyeok/AndroidStudy/app/src/main/res/layout/activity_main.xml
  dohyeok/AndroidStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  dohyeok/AndroidStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  dohyeok/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  dohyeok/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  dohyeok/AndroidStudy/app/src/main/res/values-night/themes.xml
  dohyeok/AndroidStudy/app/src/main/res/values/colors.xml
  dohyeok/AndroidStudy/app/src/main/res/values/strings.xml
  dohyeok/AndroidStudy/app/src/main/res/values/themes.xml
  dohyeok/AndroidStudy/app/src/main/res/xml/backup_rules.xml
  dohyeok/AndroidStudy/app/src/main/res/xml/data_extraction_rules.xml
  dohyeok/AndroidStudy/app/src/test/java/com/dohyeok/androidstudy/ExampleUnitTest.kt
  dohyeok/AndroidStudy/build.gradle.kts
  dohyeok/AndroidStudy/gradle.properties
  dohyeok/AndroidStudy/gradle/wrapper/gradle-wrapper.jar
  dohyeok/AndroidStudy/gradle/wrapper/gradle-wrapper.properties
  dohyeok/AndroidStudy/gradlew
  dohyeok/AndroidStudy/gradlew.bat
  dohyeok/AndroidStudy/settings.gradle.kts
Labels: 🔥 PR, 🍏 안드로이드, 🐈 도혁

#3 [#2] 프로젝트 초기 셋팅
  kwanhee/AndroidStudy/.gitignore
  kwanhee/AndroidStudy/.idea/.gitignore
  kwanhee/AndroidStudy/.idea/.name
  kwanhee/AndroidStudy/.idea/compiler.xml
  kwanhee/AndroidStudy/.idea/gradle.xml
  kwanhee/AndroidStudy/.idea/kotlinc.xml
  kwanhee/AndroidStudy/.idea/misc.xml
  kwanhee/AndroidStudy/.idea/vcs.xml
  kwanhee/AndroidStudy/app/.gitignore
  kwanhee/AndroidStudy/app/build.gradle.kts
  kwanhee/AndroidStudy/app/proguard-rules.pro
  kwanhee/AndroidStudy/app/src/androidTest/java/com/koreatech/android_study/ExampleInstrumentedTest.kt
  kwanhee/AndroidStudy/app/src/main/AndroidManifest.xml
  kwanhee/AndroidStudy/app/src/main/java/com/koreatech/android_study/MainActivity.kt
  kwanhee/AndroidStudy/app/src/main/res/drawable/ic_launcher_background.xml
  kwanhee/AndroidStudy/app/src/main/res/drawable/ic_launcher_foreground.xml
  kwanhee/AndroidStudy/app/src/main/res/layout/activity_main.xml
  kwanhee/AndroidStudy/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  kwanhee/AndroidStudy/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  kwanhee/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  kwanhee/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  kwanhee/AndroidStudy/app/src/main/res/values-night/themes.xml
  kwanhee/AndroidStudy/app/src/main/res/values/colors.xml
  kwanhee/AndroidStudy/app/src/main/res/values/strings.xml
  kwanhee/AndroidStudy/app/src/main/res/values/themes.xml
  kwanhee/AndroidStudy/app/src/main/res/xml/backup_rules.xml
  kwanhee/AndroidStudy/app/src/main/res/xml/data_extraction_rules.xml
  kwanhee/AndroidStudy/app/src/test/java/com/koreatech/android_study/ExampleUnitTest.kt
  kwanhee/AndroidStudy/build.gradle.kts
  kwanhee/AndroidStudy/gradle.properties
  kwanhee/AndroidStudy/gradle/wrapper/gradle-wrapper.jar
  kwanhee/AndroidStudy/gradle/wrapper/gradle-wrapper.properties
  kwanhee/AndroidStudy/gradlew
  kwanhee/AndroidStudy/gradlew.bat
  kwanhee/AndroidStudy/settings.gradle.kts
Labels: 🔥 PR, 🍏 안드로이드, 🐇 관희, 😎 우수

#10 [#8] 프로젝트 초기세팅
  hyoseak/AndroidStudy/.gitignore
  hyoseak/AndroidStudy/.idea/.gitignore
  hyoseak/AndroidStudy/.idea/compiler.xml
  hyoseak/AndroidStudy/.idea/gradle.xml
  hyoseak/AndroidStudy/.idea/kotlinc.xml
  hyoseak/AndroidStudy/.idea/misc.xml
  hyoseak/AndroidStudy/.idea/vcs.xml
  hyoseak/AndroidStudy/app/.gitignore
  hyoseak/AndroidStudy/app/build.gradle
  hyoseak/AndroidStudy/app/proguard-rules.pro
  hyoseak/AndroidStudy/app/src/androidTest/java/com/example/androidstudy/ExampleInstrumentedTest.kt
  hyoseak/AndroidStudy/app/src/main/AndroidManifest.xml
  hyoseak/AndroidStudy/app/src/main/java/com/example/androidstudy/MainActivity.kt
  hyoseak/AndroidStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  hyoseak/AndroidStudy/app/src/main/res/drawable/ic_launcher_background.xml
  hyoseak/AndroidStudy/app/src/main/res/layout/activity_main.xml
  hyoseak/AndroidStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  hyoseak/AndroidStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  hyoseak/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  hyoseak/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  hyoseak/AndroidStudy/app/src/main/res/values-night/themes.xml
  hyoseak/AndroidStudy/app/src/main/res/values/colors.xml
  hyoseak/AndroidStudy/app/src/main/res/values/strings.xml
  hyoseak/AndroidStudy/app/src/main/res/values/themes.xml
  hyoseak/AndroidStudy/app/src/main/res/xml/backup_rules.xml
  hyoseak/AndroidStudy/app/src/main/res/xml/data_extraction_rules.xml
  hyoseak/AndroidStudy/app/src/test/java/com/example/androidstudy/ExampleUnitTest.kt
  hyoseak/AndroidStudy/build.gradle
  hyoseak/AndroidStudy/gradle.properties
  hyoseak/AndroidStudy/gradle/wrapper/gradle-wrapper.jar
  hyoseak/AndroidStudy/gradle/wrapper/gradle-wrapper.properties
  hyoseak/AndroidStudy/gradlew
  hyoseak/AndroidStudy/gradlew.bat
  hyoseak/AndroidStudy/settings.gradle
Labels: 🔥 PR, 🍏 안드로이드, 🐧 효석

#11 #6 프로젝트 초기 세팅
  .github/pull_request_template.md
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  sumin/.gitignore
  sumin/.idea/.gitignore
  sumin/.idea/.name
  sumin/.idea/compiler.xml
  sumin/.idea/deploymentTargetDropDown.xml
  sumin/.idea/dictionaries
  sumin/.idea/gradle.xml
  sumin/.idea/kotlinc.xml
  sumin/.idea/migrations.xml
  sumin/.idea/misc.xml
  sumin/.idea/vcs.xml
  sumin/app/.gitignore
  sumin/app/build.gradle.kts
  sumin/app/proguard-rules.pro
  sumin/app/src/androidTest/java/com/wateralsie/androidstudy/ExampleInstrumentedTest.kt
  sumin/app/src/main/AndroidManifest.xml
  sumin/app/src/main/java/com/wateralsie/androidstudy/MainActivity.kt
  sumin/app/src/main/res/drawable/ic_launcher_background.xml
  sumin/app/src/main/res/drawable/ic_launcher_foreground.xml
  sumin/app/src/main/res/layout/activity_main.xml
  sumin/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  sumin/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  sumin/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  sumin/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  sumin/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  sumin/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  sumin/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  sumin/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  sumin/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  sumin/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  sumin/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  sumin/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  sumin/app/src/main/res/values-night/themes.xml
  sumin/app/src/main/res/values/colors.xml
  sumin/app/src/main/res/values/strings.xml
  sumin/app/src/main/res/values/themes.xml
  sumin/app/src/main/res/xml/backup_rules.xml
  sumin/app/src/main/res/xml/data_extraction_rules.xml
  sumin/app/src/test/java/com/wateralsie/androidstudy/ExampleUnitTest.kt
  sumin/build.gradle.kts
  sumin/gradle.properties
  sumin/gradle/libs.versions.toml
  sumin/gradle/wrapper/gradle-wrapper.jar
  sumin/gradle/wrapper/gradle-wrapper.properties
  sumin/gradlew
  sumin/gradlew.bat
  sumin/settings.gradle.kts
Labels: 🐳 수민, 🔥 PR, 🍏 안드로이드

#13 #7 프로젝트 초기 세팅
  .idea/.gitignore
  .idea/modules.xml
  .idea/study-android.iml
  sangil/AndroidStudy/.gitignore
  sangil/AndroidStudy/.idea/.gitignore
  sangil/AndroidStudy/.idea/gradle.xml
  sangil/AndroidStudy/.idea/migrations.xml
  sangil/AndroidStudy/.idea/misc.xml
  sangil/AndroidStudy/app/.gitignore
  sangil/AndroidStudy/app/build.gradle.kts
  sangil/AndroidStudy/app/proguard-rules.pro
  sangil/AndroidStudy/app/src/androidTest/java/com/strone/androidstudy/ExampleInstrumentedTest.kt
  sangil/AndroidStudy/app/src/main/AndroidManifest.xml
  sangil/AndroidStudy/app/src/main/java/com/strone/androidstudy/MainActivity.kt
  sangil/AndroidStudy/app/src/main/res/drawable/ic_launcher_background.xml
  sangil/AndroidStudy/app/src/main/res/drawable/ic_launcher_foreground.xml
  sangil/AndroidStudy/app/src/main/res/layout/activity_main.xml
  sangil/AndroidStudy/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  sangil/AndroidStudy/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  sangil/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  sangil/AndroidStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  sangil/AndroidStudy/app/src/main/res/values-night/themes.xml
  sangil/AndroidStudy/app/src/main/res/values/colors.xml
  sangil/AndroidStudy/app/src/main/res/values/strings.xml
  sangil/AndroidStudy/app/src/main/res/values/themes.xml
  sangil/AndroidStudy/app/src/main/res/xml/backup_rules.xml
  sangil/AndroidStudy/app/src/main/res/xml/data_extraction_rules.xml
  sangil/AndroidStudy/app/src/test/java/com/strone/androidstudy/ExampleUnitTest.kt
  sangil/AndroidStudy/build.gradle.kts
  sangil/AndroidStudy/gradle.properties
  sangil/AndroidStudy/gradle/wrapper/gradle-wrapper.jar
  sangil/AndroidStudy/gradle/wrapper/gradle-wrapper.properties
  sangil/AndroidStudy/gradlew
  sangil/AndroidStudy/gradlew.bat
  sangil/AndroidStudy/settings.gradle.kts
Labels: 🔥 PR, 🍏 안드로이드, 🐤 상일
